### ISSUE TITLE
部分srt字幕文件为空

### ISSUE THREAD

**Issue by lzqlzzq** [A-Soul-Database/A-Soul-Data#2]
这些字幕文件是空的：["BV12D4y1F7t4-1.srt", "BV1Bf4y1K7Nu-2.srt", "BV1C3411r7LA-3.srt", "BV1CQ4y1m7jW.srt", "BV1Dg41157CH.srt", "BV1mv411P7Vz-1.srt", "BV1mv411P7Vz-2.srt", "BV1WR4y1H7Vy.srt"]

**Comment by P-PPPP** [comment]
这些文件,大部分是回马枪和歌舞表演,字幕转换结果为空.
